export const REASONS = [
  'Expand your professional network.',
  'Learn new skills and tools.',
  'Meet industry experts.',
  'Stay up-to-date with industry trends and ideas.',
  "Meet people who understand your 'Ruby humor' and appreciate your programming jokes.",
  'To see if you can convince the locals to rename the city Vilnius-Ruby-on-Rails.',
  'Have fun and socialize.',
  'Get inspired.',
  'Find new career opportunities.',
  "To prove to your mom that you do have friends (and they're all Ruby programmers!).",
  'Develop new business relationships.',
  'Access vendors and suppliers.',
  'Gain exposure to different perspectives.',
  'Develop your professional skills and knowledge.',
  'Because you want to visit every European city that has ever hosted Euruko, and become the ultimate Euruko tourist.',
  'Build brand awareness.',
  'Learn from other professionals.',
  'Gain insights into emerging technologies.',
  'Meet potential collaborators.',
  'To see how many sessions you can attend without dozing off or getting distracted by your phone.',
  'Numerous cafes, bars, and pubs to socialize with other attendees and unwind after a long day of learning and networking.',
  'To debate with other Euruko attendees about which bar or restaurant has the best food, drinks, and atmosphere.',
  'Learn about new markets and opportunities.',
  'Connect with peers.',
  'Get feedback on your work.',
  'Access thought leaders.',
  'To find new friends who can help you solve all your Ruby programming problems, and maybe even your personal problems too.',
  'Celebrating the 30th anniversary of Ruby.',
  'Opportunity to reflect on the history and evolution of Ruby, as well as its impact on the world of programming.',
  'Stay motivated and energized.',
  'Get hands-on experience with new technologies.',
  'Attend workshops and training sessions.',
  'Discover new tools and resources to enhance your work.',
  'Networking at Euruko is like speed-dating for developers. Just swap out the awkward silences with awkward code questions!',
  'Get exposure to different industries and sectors.',
  'Learn about the latest research and developments.',
  'Participate in panel discussions and debates.',
  'Attend keynote speeches by industry leaders.',
  "Because nothing says 'I'm a serious programmer' like wearing a conference merch for weeks after the event.",
  'Discover new approaches and methodologies.',
  'Take advantage of networking events.',
  'Showcase your own work and projects.',
  'Learn about funding opportunities and grants.',
  "Because you're convinced that the best way to learn Ruby programming is to surround yourself with other Ruby enthusiasts, and Euruko is the perfect place to do that.",
  'Get advice on career development and advancement.',
  'Attend industry-specific tracks and sessions.',
  'Learn about best practices and case studies.',
  'Participate in hackathons and coding challenges.',
  "Because you're convinced that a group photo with a bunch of Ruby programmers will make you look more intelligent.",
  'Get access to exclusive content and resources.',
  'Meet potential investors and partners.',
  'Learn about the latest tools and techniques for remote work.',
  'Attend sessions on diversity, equity, and inclusion.',
  "Create a Ruby-powered app that tells you how long you've been staring at your computer screen.",
  'Expand your knowledge and expertise in your field.',
  'Discover new business models and strategies.',
  'Learn about the latest marketing techniques.',
  'Attend sessions on project management and collaboration.',
  "Because you're convinced that Lithuanian beer is the secret to mastering Ruby programming, and you're determined to try every kind.",
  'Learn how to improve team productivity and efficiency.',
  'Get exposure to different coding languages and frameworks.',
  "To prove to your old friend that you've become a Ruby programming superstar since the last time you met.",
  'Discover new job opportunities and career paths.',
  'Learn how to develop a successful startup.',
  'Who knows, you might just end up accidentally starting your own startup with your new Euruko pals.',
  'Meet potential mentors and advisors.',
  'Attend sessions on cybersecurity and data privacy.',
  'Learn how to optimize your website for search engines.',
  'Discover new trends in user experience and design.',
  "To finally have an excuse to wear that fancy outfit you've been saving for a special occasion.",
  'Attend sessions on software testing and quality assurance.',
  'Learn about the latest trends in mobile app development.',
  'Participate in workshops on agile development and Scrum.',
  'Discover new ways to monetize your online business.',
  'Attend sessions on data analysis and visualization.',
  'Learn how to develop your own mobile app.',
  'Discover new open-source projects and communities.',
  'Attend sessions on cloud computing and DevOps.',
  'Get exposure to different career paths in tech.',
  'Meet potential clients and customers.',
  'Learn how to improve your software architecture.',
  'Discover new approaches to software development.',
  'Attend sessions on software performance and scalability.',
  'Learn about the latest advances in artificial intelligence and machine learning.',
  'Discover new tools and techniques for data science.',
  'Participate in coding challenges and competitions.',
  'Learn how to improve your public speaking and presentation skills.',
  'Attend sessions on leadership and team building.',
  'Get exposure to different entrepreneurship and startup communities.',
  'Discover new tools and techniques for project management.',
  'Attend sessions on agile marketing and growth hacking.',
  'Learn how to develop a successful social media strategy.',
  'Discover new ways to build and monetize a personal brand.',
  'Attend sessions on personal and professional development.',
  'Learn about the latest trends in blockchain technology.',
  'Discover new ways to leverage big data for business insights.',
  'Attend sessions on UX writing and content strategy.',
  'Learn how to develop your own chatbot or voice assistant.',
  'Get exposure to different perspectives on the future of technology.',
  'Discover new approaches to software testing and quality assurance.',
  'Learn about the latest advances in virtual and augmented reality.',
  'Attend sessions on designing for accessibility and inclusivity.',
  'Get exposure to different approaches to data visualization and storytelling.',
  'Learn how to build a successful e-commerce business.',
  'Discover new tools and techniques for mobile game development.',
  'Attend sessions on open-source software and community building.',
  'Learn how to leverage data analytics for business intelligence.',
  'Get exposure to different approaches to content creation and distribution.',
  'Attend sessions on cloud-native architecture and microservices.',
  'Learn how to improve your cybersecurity and data privacy practices.',
  'Discover new trends in the Internet of Things (IoT).',
  'Attend sessions on developing for voice and chat interfaces.',
  'Learn how to develop a successful content marketing strategy.',
  'Get exposure to different approaches to machine learning and data science.',
  'Attend sessions on developing wearable technology.',
  'Learn how to develop a successful digital marketing campaign.',
  'Discover new trends in cybersecurity and online safety.',
  'Attend sessions on developing for the decentralized web.',
  'Learn how to leverage social media for business growth.',
  'Party with Ruby developers at the conference after-party.',
  'Enjoy the sights and sounds of the host city while attending an amazing conference.',
  'Get a chance to show off your favorite Ruby-themed fashion.',
  'Discover new ways to incorporate Ruby into your daily life, beyond just programming.',
  'Enjoy delicious food and drinks while mingling with fellow conference-goers.',
  'Dance the night away to great music with a crowd that shares your interests.',
  'Get the chance to bond with your favorite conference speakers over a few drinks.',
  'Take part in fun activities like photo booths or games that make for great memories and bonding experiences.',
  'Share and discuss ideas.',
  'Discover new tools and techniques for DevOps and automation.',
  'Learn about the latest trends in cloud computing and serverless architecture.',
  'Attend sessions on developing for the Internet of Things (IoT).',
  'Get exposure to different approaches to artificial intelligence and machine learning.',
  'Learn how to develop a successful content creation strategy.',
  'Discover new tools and techniques for web development.',
  'Attend sessions on developing for virtual and augmented reality.',
  'Learn how to improve your data management and analytics practices.',
  'Get exposure to different approaches to software engineering and architecture.',
  'Attend sessions on developing for blockchain and cryptocurrency.',
  'Learn how to develop a successful SEO strategy.',
  'Discover new trends in social media marketing and advertising.',
  'Attend sessions on developing for the smart home and connected devices.',
  'Learn how to leverage data analytics for customer insights and engagement.',
  'Get exposure to different approaches to cloud-native development.',
  'Attend sessions on developing for the cloud and hybrid environments.',
  'Learn how to develop a successful influencer marketing strategy.',
  'Discover new tools and techniques for data engineering and management.',
  'Attend sessions on developing for voice assistants and chatbots.',
  'Learn how to improve your customer experience and user engagement.',
  'Learn about the best practices and standards for writing clean, maintainable Ruby code.',
  'Discover new tools and techniques for debugging and profiling Ruby applications.',
  'Attend sessions on developing Ruby applications for mobile platforms, such as iOS or Android.',
  'Get exposure to different approaches to building APIs with Ruby.',
  'Learn how to implement test-driven development (TDD) in your Ruby projects.',
  'Attend sessions on using Ruby in robotics and automation projects.',
  'Discover new ways to use Ruby in game development and design.',
  'Learn how to build real-time applications with Ruby and websockets.',
  'Attend sessions on using Ruby for scripting and automation in system administration.',
  'Get exposure to different approaches to functional programming with Ruby.',
  'Learn about the latest developments in Ruby web development, such as using Webpack or Stimulus.',
  'Attend sessions on using Ruby in DevOps and infrastructure automation.',
  'Discover new tools and techniques for working with databases in Ruby applications.',
  'Learn how to use Ruby in developing chatbots and voice assistants.',
  'Attend sessions on using Ruby for data visualization and analysis.',
  'Get exposure to different approaches to building microservices with Ruby.',
  'Learn how to use Ruby in developing desktop applications.',
  'Attend sessions on using Ruby in blockchain and cryptocurrency projects.',
  'Discover new tools and techniques for working with APIs and web services in Ruby.',
  'Hear from industry leaders and experts on the latest trends and innovations in technology.',
  'Learn from the experiences and insights of successful entrepreneurs and business leaders.',
  'Get inspired by keynote speeches from prominent figures in the tech industry.',
  'Attend interactive sessions with renowned developers and software engineers.',
  'Learn from the perspectives of diverse speakers from different backgrounds and industries.',
  'Gain new perspectives and insights on technology and its impact on society.',
  'Meet and network with speakers and other attendees to build valuable connections.',
  'Attend sessions led by influential thought leaders and change-makers in the tech industry.',
  'Learn about the challenges and opportunities facing the tech industry from experienced speakers.',
  'Get exposure to new ideas and emerging technologies from cutting-edge speakers.',
  'Attend Q&A sessions with speakers to gain a deeper understanding of their expertise.',
  'Learn from the experiences and successes of startup founders and early-stage investors.',
  'Attend workshops and training sessions led by industry experts to improve your skills.',
  'Get inspired by the journeys and lessons learned of speakers who have faced adversity and overcome challenges.',
  'Attend sessions led by experienced educators and trainers who specialize in tech education.',
  'Gain insights into the latest research and academic developments in technology from expert speakers.',
  'Hear from speakers who are leading the way in open source and community-driven development.',
  'Attend sessions led by prominent figures in the tech policy and advocacy space.',
  'Learn about emerging career paths and opportunities in the tech industry from experienced speakers.',
  'Learn about the different Ruby communities and their unique perspectives and approaches.',
  'Attend sessions led by members of prominent Ruby communities, such as Ruby on Rails or Sinatra.',
  'Network with Ruby community leaders to learn about opportunities for involvement and contribution.',
  'Get exposure to the latest developments and trends in the Ruby community.',
  'Attend sessions on the history and evolution of the Ruby programming language and its communities.',
  'Learn how to get involved in the Ruby community and make meaningful contributions.',
  'Attend workshops and training sessions led by prominent members of the Ruby community.',
  'Get advice and guidance on improving your Ruby skills from experienced community members.',
  'Learn about the different Ruby job markets and opportunities available to Ruby developers.',
  'Hear from Ruby community leaders about the future direction of the language and its communities.',
  'Attend sessions on best practices for collaborating and working within Ruby communities.',
  'Learn about the diverse range of applications and use cases for the Ruby programming language.',
  'Connect with Ruby developers and enthusiasts who are working on cutting-edge projects and technologies.',
  'Attend sessions on building and maintaining successful open source Ruby projects and communities.',
  'Get exposure to the different ways Ruby is being used in various industries and domains.',
  'Learn about the different tools and libraries available to Ruby developers through community contributions.',
  'Attend sessions on developing and maintaining inclusive and welcoming Ruby communities.',
  'Meet Ruby community leaders and contributors to gain a deeper understanding of the Ruby ecosystem.',
  'Enjoy socializing and networking with other attendees in a relaxed setting.',
  'Connect with other attendees who share your interests and passions outside of technology.',
  'Meet speakers and organizers in a more informal and fun environment.',
  'Experience the local nightlife and culture of the host city.',
  'Get exposure to new and exciting local foods and drinks at afterparties.',
  'Attend themed parties and events with creative and entertaining activities.',
  'Dance and have fun with fellow attendees to great music and entertainment.',
  'Participate in team-building and group activities to make new connections.',
  'Enjoy a change of pace and decompress after a day of intense learning and professional development.',
  'Build lasting memories and friendships with other attendees and organizers.',
  'Celebrate the 30th anniversary of the Ruby programming language with fellow enthusiasts and developers.',
  'Learn about the history and evolution of the Ruby language and its impact on the tech industry.',
  'Hear from the creators and early pioneers of Ruby about their experiences and insights.',
  "Attend special sessions and events commemorating Ruby's milestone anniversary.",
  'Get inspired by the passion and dedication of the Ruby community in advancing the language and its ecosystem.',
  'Meet other Ruby enthusiasts and developers who share your love for the language.',
  'Learn about the latest developments and trends in the Ruby community and how they relate to the anniversary.',
  "Attend workshops and training sessions specifically geared towards celebrating Ruby's anniversary.",
  'Discover new ways to contribute to the Ruby community and its future growth and development.',
  'Have fun and enjoy special activities and events organized to celebrate this special occasion.',
  'Discover how Ruby can be used for social good and humanitarian projects.',
  'Attend a talk by a Ruby developer who has incorporated the language into their art installations.',
  'Learn how Ruby is being used in scientific research and innovation.',
  'Participate in a panel discussion on the future of programming languages and their potential impact on society.',
  'Hear from Ruby developers who have created innovative solutions to social, environmental, or economic issues using the language.',
  'Attend a workshop on using Ruby to create interactive and immersive experiences.',
  'Free cookies and coffee!',
  'Meet a robot programmed to appreciate bad jokes.',
  'Attend a seminar on how to teach Ruby to your pets.',
  'Learn how Ruby can be used to program the perfect sandwich.',
  "Join a discussion on how to use Ruby to solve the world's most pressing problems, such as how to make toast without burning it.",
  'Discover how Ruby can be used to program a time machine that can only go back five minutes.',
  'Attend a talk on how to use Ruby to program a pet rock.',
  'Participate in a workshop on how to use Ruby to program a potato to play tic-tac-toe.',
  'Learn how to use Ruby to create a language-learning app for houseplants.',
  'Discover how Ruby can be used to program a robot to dance the Macarena.',
  'Explore the charming and historic Old Town of Vilnius, a UNESCO World Heritage site.',
  'Learn about Lithuanian culture and history through its art, architecture, and museums.',
  'Sample the delicious and diverse local cuisine, from traditional Lithuanian dishes to contemporary fusion cuisine.',
  'Enjoy the vibrant and lively nightlife of Vilnius, with a variety of bars, clubs, and entertainment venues.',
  'Take advantage of the affordable prices of Vilnius compared to other European cities.',
  'Experience the warmth and hospitality of Lithuanian people, known for their friendliness and helpfulness.',
  'Discover the beautiful natural landscapes of Lithuania, including forests, lakes, and rivers.',
  'Attend cultural events and festivals happening in Vilnius during the conference, such as music or film festivals.',
  'Visit nearby attractions like Trakai Castle, a beautiful medieval castle situated on a lake just outside of Vilnius.',
  'Connect with other attendees and locals through organized tours and activities, such as city walks or bike tours.',
  'Gain a competitive edge in your career by staying up-to-date with the latest trends and innovations in Ruby programming.',
  'Learn new skills and techniques from experienced speakers and trainers that can help you advance your career and achieve your goals.',
  'Expand your professional network by meeting and connecting with other like-minded professionals and potential employers.',
  'Attend specialized sessions and workshops tailored to your specific interests and skill level.',
  'Discover new tools and technologies that can help you work more efficiently and effectively.',
  'Share your knowledge and insights with others by participating in lightning talks, panel discussions, or open space sessions.',
  'Connect with potential clients or collaborators who can help you grow your business or start a new project.',
  'Get inspired by hearing success stories and personal journeys of other developers and entrepreneurs in the Ruby community.',
  'Receive valuable feedback and advice on your own projects or code by engaging with other developers and experts.',
  'Have fun and enjoy a unique and enriching experience that can help you grow both professionally and personally.',
  'Celebrate the 20th anniversary of Euruko, the premier European conference for Ruby developers and enthusiasts.',
  'Learn about the history of Euruko and how it has grown and evolved over the years.',
  'Hear from the organizers and early pioneers of Euruko about their experiences and insights.',
  "Attend special sessions and events commemorating Euruko's milestone anniversary.",
  'Meet other Euruko attendees and enthusiasts who have been attending the conference for years.',
  'Discover how the Euruko community has impacted the Ruby ecosystem and the tech industry as a whole.',
  'Participate in team-building and group activities to connect with other Euruko attendees and organizers.',
  "Learn about the latest developments and trends in the Ruby community and how they relate to Euruko's anniversary.",
  "Attend workshops and training sessions specifically geared towards celebrating Euruko's anniversary.",
  'Celebrate this special occasion with a community of like-minded individuals who share your passion for Ruby and its ecosystem.',
  'Develop your communication skills by learning from experienced speakers who can teach you how to articulate your ideas and present them effectively.',
  'Practice your networking skills by meeting and engaging with other attendees from different backgrounds and industries.',
  'Learn how to communicate technical concepts in a way that is accessible and easy to understand for non-technical stakeholders.',
  'Attend sessions and workshops that focus specifically on communication skills, such as public speaking, storytelling, or team collaboration.',
  'Engage in open space sessions or panel discussions to share your own experiences and insights with others in the Ruby community.',
  'Connect with speakers and other experts in the field who can provide valuable feedback and mentorship.',
  'Practice active listening and empathy by engaging with other attendees and learning about their perspectives and experiences.',
  'Develop cross-cultural communication skills by interacting with attendees from different countries and backgrounds.',
  'Learn how to navigate difficult conversations and conflicts in a professional and constructive manner.',
  'Improve your ability to work collaboratively and effectively with others by learning how to communicate and negotiate in a team environment.',
  'Immerse yourself in a dynamic and inspiring environment that can spark creativity and innovation.',
  'Attend sessions and workshops that are specifically designed to be interactive and engaging, giving you a more hands-on experience.',
  'Participate in team-building and social events that can help you connect with other attendees and build lasting relationships.',
  'Take advantage of opportunities to explore Vilnius, the host city of Euruko, and its unique culture and history.',
  'Experience the excitement and energy of being part of a community of passionate and like-minded individuals.',
  'Gain a broader perspective on the Ruby ecosystem and the tech industry by hearing from speakers and attendees with diverse backgrounds and experiences.',
  "Get access to exclusive content and insights that you won't find anywhere else.",
  'Take the opportunity to unplug and disconnect from your daily routine to focus on learning and personal growth.',
  "Experience the thrill of discovering new ideas and insights that can help you push the boundaries of what's possible.",
  'Come away from the conference feeling inspired, energized, and ready to take your career to the next level.',
  'Gain new insights and perspectives on Ruby and its ecosystem from experienced speakers and experts in the field.',
  'Attend hands-on workshops and training sessions to improve your technical skills and knowledge.',
  'Learn about the latest trends and developments in the Ruby community and how they are shaping the future of tech.',
  'Discover new tools and techniques that can help you streamline your workflow and improve your productivity.',
  'Connect with other learners and educators in the Ruby community and exchange knowledge and ideas.',
  'Attend sessions and workshops that cater to different learning styles and preferences, including visual, auditory, and kinesthetic learners.',
  'Access resources and materials that can help you continue your learning journey even after the conference is over.',
  'Learn about the best practices and industry standards in Ruby development and how to apply them in your own work.',
  'Attend sessions and workshops that address common challenges and roadblocks that developers face in their work and learn how to overcome them.',
  'Gain a deeper understanding of the Ruby ecosystem and its role in the wider tech industry.',
  'Attend a talk on how Ruby can be used to create a language for communicating with extraterrestrial life.',
  'Attend a seminar on how to use Ruby to program a talking tree that dispenses wise advice.',
  'Enjoy pizza and drinks while talking about your favorite Ruby memes with other attendees.',
  'Participate in a karaoke contest where you can sing your favorite Ruby-related songs (or any other song, really).',
  "Learn from industry leaders and innovators who are pushing the boundaries of what's possible in Ruby development.",
  'Explore new frameworks and tools that can help you streamline your workflow and build better software.',
  'Get feedback on your work and projects from experienced developers who can help you improve and grow.',
  'Discover new ways to collaborate with others and build stronger, more effective teams.',
  'Learn about the latest trends and emerging technologies that are shaping the future of Ruby and the tech industry.',
  'Connect with peers and mentors who can provide guidance, support, and inspiration.',
  'Be inspired by the passion and enthusiasm of the Ruby community, and tap into the collective energy of like-minded individuals.',
  'Experience the thrill of solving complex problems and challenges in real-time, and develop new skills and knowledge in the process.',
  'Build your personal and professional network, and forge lasting relationships that can support you throughout your career.',
  'Take a break from your daily routine, and immerse yourself in an environment of creativity, innovation, and inspiration.',
  "Because Ruby is not just a shiny gemstone, it's a shiny programming language.",
  'To discover why every programmer needs a little Ruby in their life.',
  'Because you secretly want to join the elite group of programmers who know the difference between Ruby and RuPaul.',
  'To prove once and for all that the best way to learn programming is by attending conferences and eating unlimited snacks.',
  'Expand your knowledge and skills in Ruby and related technologies.',
  'Discover new ways to solve problems and overcome challenges in your work.',
  'Network with peers and industry experts who can help you advance your career.',
  'Learn about the latest trends and developments in the tech industry, and how they impact your work.',
  'Gain access to exclusive resources and materials that can help you grow and learn.',
  'Meet and connect with like-minded individuals who share your passion for Ruby and software development.',
  'Be inspired by innovative ideas and creative solutions to common problems.',
  'Have fun, unwind, and explore a new city while learning and growing professionally.',
  'Boost your confidence and self-esteem by challenging yourself and stepping out of your comfort zone.',
  'Improve your problem-solving and critical thinking skills by attending workshops and participating in hands-on activities.',
  'Access to practical and applicable knowledge that you can immediately apply to your work.',
  'Exposure to diverse perspectives and approaches to software development.',
  'Opportunity to showcase your skills and knowledge by presenting a talk or participating in a workshop.',
  'Discover potential collaborators for your current or future projects.',
  'Develop relationships with sponsors and potential employers.',
  "So you can update your LinkedIn profile with a picture that doesn't look like a mugshot.",
  'Because you need photographic evidence that you were part of the coolest group of programmers on the planet.',
  'To show your grandkids that you were once young and hip (even if it was just for a weekend).',
  'Discover new and emerging technologies in the Ruby ecosystem.',
  'Learn how to leverage existing technologies to improve your software development process.',
  'Stay up-to-date with the latest tools, frameworks, and libraries.',
  'Gain insights into the best practices for using Ruby and related technologies.',
  'Explore how to integrate new technologies into your current software development workflow.',
  "To see if the conference organizers were able to find a venue that's bigger on the inside.",
  "To see if the conference organizers were able to find a venue that's earthquake-proof, zombie-proof, and unicorn-proof.",
  'Comfortable and spacious seating areas for networking and socializing with other attendees.',
  'Easy to navigate and well-organized, ensuring a smooth and enjoyable experience for attendees.',
  'To see if your hotel room comes with a personal butler who will serve you breakfast in bed and code Ruby with you.',
  'Opportunity to connect and network with other attendees who are also staying at the same hotel.',
  "To prove to your friends that you're so smart, you can code in Ruby and recite the entire Lithuanian national anthem from memory at the same time.",
  'Vilnius, the capital city of Lithuania, is one of the most beautiful and charming cities in Europe.',
  'Lithuania is home to many universities and research centers, making it a hub for innovation and entrepreneurship.',
  'Lithuania is known for its natural beauty, with forests, lakes, and beaches that are perfect for outdoor activities and adventures.',
  "Because you're secretly hoping to meet your Ruby programming soulmate and live happily ever after coding together.",
  "To make new friends who are so passionate about Ruby programming that they'll never judge you for spending all weekend coding instead of going outside.",
  'Participate in social events and activities designed to foster networking and relationship-building.',
  'Attendees come from all over the world, providing a unique opportunity to make connections on a global scale.',
  "Because you're convinced that the best way to showcase your Ruby programming skills is to combine it with a stand-up comedy routine.",
  'To see if you can give the most entertaining and engaging Ruby programming talk in Euruko history, and maybe even win a prize for it.',
  'Opportunity to receive feedback and insights from other experts in the field.',
  'Potential to gain exposure and increase visibility within the Ruby community.',
  'Platform to share new and innovative ideas with others who are passionate about technology.',
  'Participate in a collaborative and supportive community of developers, helping to improve your own skills and knowledge.',
  "To see if you can learn Ruby programming so well that you'll never have to leave your house again, because you'll be able to code your way out of any situation.",
  "Because you're secretly hoping to learn the secret codes to unlock the Matrix, and you think the Euruko speakers might have some insider information.",
  'To add another stamp to your passport and show everyone on Instagram how cultured and worldly you are.',
  'To take a break from all the intense Ruby programming and go on a wild, Euruko-themed sightseeing adventure around Vilnius.',
  'To show your love for Lithuania and its people by eating as much cepelinai and šaltibarščiai as humanly possible.',
  'To celebrate your newfound Ruby programming knowledge with a cold, refreshing beer (or two, or three...).',
  "Because let's face it, there's nothing quite like a cold beer after a long day of learning and networking at Euruko.",
  'Many of the bars and restaurants are located within walking distance of the conference venue, making it easy to explore the city and enjoy the local food and drinks.',
  'Opportunity to sample and enjoy Lithuanian beer, which is known for its high quality and unique flavors.',
  'Opportunity to capture memories with new friends and colleagues from around the world.',
  'To finally settle that age-old debate about whether tabs or spaces are better for coding.',
  'To experience Vilnius nightlife and see what the city has to offer after hours.',
  'To bond with other attendees over shared love for certain types of music or dancing styles.',
  'To challenge yourself to attend sessions on topics you know nothing about just for the sake of broadening your knowledge.',
  'A diverse and engaging conference agenda featuring talks, workshops, and networking events.',
  'Opportunity to learn from and engage with some of the most talented and knowledgeable Ruby developers in the world.',
  'Topics covering the latest trends, technologies, and best practices in the Ruby community.',
  'Access to practical knowledge and insights that can be applied to your work and projects immediately.',
  'Chance to gain a deeper understanding of the Ruby programming language and its applications in various industries.',
  "To witness the conference organizers attempt to fit 20 candles on a cake that's too small.",
  "To compete in a 'Name That Ruby Version' game show, featuring all the past and present versions of the language.",
  "To participate in a 'Guess That Speaker' game, where attendees have to identify famous Ruby developers based on their baby photos.",
  "To learn Lithuanian so you can give an impromptu speech about Vilnius's 700-year history at a local bar (after a few drinks, of course).",
  "Participating in the many special events and activities planned throughout the year to mark the city's 700th anniversary, such as concerts, exhibitions, and festivals.",
  'To see if any of the conference sessions are dedicated to learning medieval Lithuanian folk dances.',
  "Celebrating the rich history and cultural heritage of Vilnius, one of Europe's most beautiful and vibrant cities.",
  "Opportunity to explore Vilnius' stunning architecture, including Gothic, Baroque, and Renaissance styles.",
  "To experience the thrill of sitting in a chair so comfortable you'll never want to stand up again.",
  'To learn how to code while balancing a cup of coffee on your lap, without spilling a drop.',
  'To enjoy the sensation of your muscles slowly melting into the plush cushions, while your brain melts into Ruby.',
  "Networking at Euruko is so good, it'll make LinkedIn jealous.",
  'You might accidentally meet your future boss, employee, or spouse!',
  "It's a chance to practice your handshaking and small talk skills.",
  "Because making friends as an adult is hard, and networking is just a fancy way of saying 'making new friends who can help you professionally.'",
  'You can finally ask someone in person to explain to you what blockchain is.',
  'By attending conference events such as workshops, breakout sessions, and after-parties, you can engage in informal conversations that can lead to new ideas and collaborations.',
  'Networking can provide you with access to new resources, information, and perspectives that you may not have encountered otherwise.',
  'Building a strong professional network can also enhance your reputation and increase your visibility within your industry.',
  'Learning from other professionals in your field by sharing insights, ideas, and best practices.',
  "To show off your love for all things coding even when you're off the clock.",
  'You get a Euruko laptop sticker to cover up that embarrassing scratch.',
  'Take a selfie with Matz and impress all your Ruby-loving friends',
  'Ask Matz to teach you Ruby in just one sentence.'
];
